/* BatchWatt V3.1: procurement-first factory decision layer. */
'use strict';
(() => {
const $=id=>document.getElementById(id), n=v=>Number(v||0), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])), usd=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n(v));
const pilots={
 rkg:{name:'RKG Ghee',id:'BW-RKG-001',dates:'Jul 7–20, 2026',orders:32,cycles:10,planning:64.2,energy:8.8,peak:11.7,rating:4.34,flow:'Urgent dispatches → reserve material → group compatible SKUs → avoid simultaneous high-load heating.',moves:['Cow Ghee 200 ml: run first; reserve bottles and confirm dispatch time.','Bulk Ghee 5 litre: stagger heating and filling around the peak window.','Cow Ghee 1 litre: group with the same cleaning family to reduce changeover.']},
 pr:{name:'PR Food Products',id:'BW-PRF-001',dates:'Jul 14–25, 2026',orders:41,cycles:9,planning:62.3,energy:6.7,peak:9.0,rating:4.26,flow:'Consolidate orders → check material → assign machines → group compatible products → protect urgent dispatches.',moves:['Idli/Dosa Mix 500 g: run first and protect urgent dispatch.','Sambar Powder 200 g: reserve the first packing slot.','Snack Mix 250 g: use available material before replenishment.']}
};
let active='rkg';
const addDays=(d,x)=>{const z=new Date(`${d}T12:00:00`);z.setDate(z.getDate()+n(x));return `${z.getFullYear()}-${String(z.getMonth()+1).padStart(2,'0')}-${String(z.getDate()).padStart(2,'0')}`};
function timing(m){const mat=(input.materials||[]).find(x=>x.id===m.materialId),sup=(input.suppliers||[]).find(x=>x.id===(m.supplierId||mat?.supplierId)),pids=new Set((input.recipes||[]).filter(x=>x.materialId===m.materialId).map(x=>x.productId)),due=(result?.allocations||[]).filter(x=>x.produce>0&&pids.has(x.productId)).map(x=>x.due).filter(Boolean).sort()[0]||'',need=due?due.slice(0,10):'',lead=n(sup?.leadDays),by=need?addDays(need,-lead):'',urgent=n(m.shortage)>0||!!(by&&by<=input.shift.date);return{sup:sup?.name||m.supplier||'Choose supplier',lead,need,urgent,label:n(m.shortage)>0?'Order now':by?(by<=input.shift.date?'Order now':`Order by ${by}`):'Replenish buffer'};}
function peak(j){const a=BatchWattEnergy.timeMinutes(input.energy.peakStart),b=BatchWattEnergy.timeMinutes(input.energy.peakEnd),s=n(j.start),e=n(j.end);return a<b?s<b&&e>a:s<b||e>a;}
function metric(a,b,c,d=false){return `<article class="metric ${d?'attention':''}"><span>${esc(a)}</span><strong>${esc(b)}</strong><small>${esc(c)}</small></article>`}
function control(){if(!result)return;const rows=statusRows(),jobs=[...result.proposed.jobs].sort((a,b)=>a.start-b.start),buys=(result.procurement.requirements||[]).filter(x=>n(x.toBuy)>0),urgent=buys.filter(x=>timing(x).urgent),spend=buys.reduce((s,x)=>s+n(x.estimatedCost),0),stock=rows.filter(x=>x.status==='Ready from stock'),ready=rows.filter(x=>['Ready from stock','Scheduled'].includes(x.status)),next=jobs[0],head=n(input.energy.peakLimitKw)-n(result.proposed.peakKw);
$('decision-buy').textContent=buys.length?`${buys.length} material${buys.length===1?'':'s'} · ${usd(spend)}`:'No purchase needed';$('decision-buy-note').textContent=buys.length?`${urgent.length} need action now.`:'Stock and incoming supply cover demand.';
$('decision-make').textContent=next?`${next.startTime} · ${next.product}`:'No production run';$('decision-make-note').textContent=next?`${next.produce} ${next.unit} on ${next.line}. ${peak(next)?'Touches peak tariff.':'Outside peak tariff.'}`:'Demand covered from stock or blocked.';
$('decision-dispatch').textContent=`${ready.length}/${rows.length} orders ready`;$('decision-dispatch-note').textContent=`${stock.length} from stock · ${result.proposed.unscheduled.length} blocked.`;
$('decision-energy').textContent=`${result.proposed.peakKw} kW peak`;$('decision-energy-note').textContent=head>=0?`${head.toFixed(1)} kW headroom · ${usd(result.proposed.usageCost)} shift charge.`:`${Math.abs(head).toFixed(1)} kW above target.`;
const acts=[];buys.sort((a,b)=>Number(timing(b).urgent)-Number(timing(a).urgent)||n(b.shortage)-n(a.shortage)).slice(0,2).forEach(m=>{const t=timing(m);acts.push(`<article class="action-card"><span class="action-icon buy">BUY</span><div><strong>${esc(t.label)}: ${m.toBuy} ${esc(m.unit)} ${esc(m.name)}</strong><p>${n(m.shortage)>0?`${m.shortage} ${esc(m.unit)} short for loaded production.`:`Protect ${m.reorderPoint} ${esc(m.unit)} buffer.`} Supplier: ${esc(t.sup)}.</p><div class="action-meta">${usd(m.estimatedCost)}${t.need?` · needed ${esc(t.need)}`:''}</div></div><button data-create-po="${esc(m.materialId)}" data-qty="${m.toBuy}">Create PO</button></article>`)});if(stock[0]){const r=stock[0];acts.push(`<article class="action-card"><span class="action-icon dispatch">SHIP</span><div><strong>Dispatch ${esc(r.product)} from stock</strong><p>${r.fromStock} ${esc(r.unit)} reserved for ${esc(r.customer)}.</p></div><button data-go="orders">View</button></article>`)}if(next)acts.push(`<article class="action-card"><span class="action-icon make">MAKE</span><div><strong>Start ${esc(next.product)} at ${esc(next.startTime)}</strong><p>${next.produce} ${esc(next.unit)} on ${esc(next.line)} · ${next.kw} kW · due ${esc(String(next.due).replace('T',' '))}</p></div><a class="button-link" href="#production-plan-anchor">Plan</a></article>`);$('priority-actions').innerHTML=acts.join('')||'<div class="empty">No immediate intervention required.</div>';$('action-count').textContent=`${acts.length} action${acts.length===1?'':'s'}`;
$('production-plan').innerHTML=jobs.map((j,i)=>`<article class="production-card"><div class="production-time"><strong>${esc(j.startTime)}</strong><span>to ${esc(j.endTime)}</span></div><div class="production-main"><h3>${i+1}. ${esc(j.product)}</h3><p>${j.produce} ${esc(j.unit)} for ${esc(j.customer)} · due ${esc(String(j.due).replace('T',' '))}</p><span class="energy-tag ${peak(j)?'peak':''}">${peak(j)?'Peak tariff overlap':'Outside peak tariff'}</span></div><div class="production-side"><strong>${esc(j.line)}</strong><p>${j.kw} kW · ${j.kwh} kWh${j.changeoverMinutes?` · ${j.changeoverMinutes}m changeover`:''}</p></div></article>`).join('')||'<div class="empty">No production required.</div>';
$('energy-ribbon-title').textContent=result.comparison.peakReductionKw?`Sequence trims peak by ${result.comparison.peakReductionKw} kW without dropping work.`:'Dispatch-first schedule retained.';$('energy-ribbon-note').textContent=result.comparison.shiftedJobs?`${result.comparison.shiftedJobs} run(s) shifted after delivery and cost checks.`:'No better energy sequence passed the delivery checks.';$('energy-ribbon-metrics').innerHTML=`<div class="ribbon-metric"><span>Peak</span><strong>${result.proposed.peakKw} kW</strong></div><div class="ribbon-metric"><span>Charge</span><strong>${usd(result.proposed.usageCost)}</strong></div>`;}
function procurement(){if(!result)return;const req=result.procurement.requirements||[],buys=req.filter(x=>n(x.toBuy)>0),urg=buys.filter(x=>timing(x).urgent),spend=buys.reduce((s,x)=>s+n(x.estimatedCost),0);$('procurement-metrics').innerHTML=[metric('Buy actions',buys.length,`${urg.length} need action now`,urg.length>0),metric('Estimated spend',usd(spend),'Configured material costs'),metric('Incoming materials',req.filter(x=>n(x.incoming)>0).length,'Materials with ordered supply'),metric('Open POs',(input.purchaseOrders||[]).filter(x=>['Draft','Ordered','Part received'].includes(x.status)).length,'Draft + ordered + partial')].join('');$('buy-plan').innerHTML=buys.map(m=>{const t=timing(m);return `<article class="buy-card ${t.urgent?'urgent':''}"><div class="buy-top"><div><span class="eyebrow">${t.urgent?'ACTION NOW':'PLANNED BUY'}</span><h3>${esc(m.name)}</h3></div><span class="pill ${t.urgent?'critical':'info'}">${esc(t.label)}</span></div><div class="quantity">${m.toBuy} <small>${esc(m.unit)}</small></div><p>${n(m.shortage)>0?`${m.shortage} ${esc(m.unit)} short for loaded production.`:`Maintains ${m.reorderPoint} ${esc(m.unit)} buffer.`}</p><div class="buy-meta"><div><span>Supplier</span><strong>${esc(t.sup)}</strong></div><div><span>Lead time</span><strong>${t.lead} days</strong></div><div><span>Needed by</span><strong>${esc(t.need||'Buffer')}</strong></div><div><span>Spend</span><strong>${usd(m.estimatedCost)}</strong></div></div><button class="primary" data-create-po="${esc(m.materialId)}" data-qty="${m.toBuy}">Create purchase order</button></article>`}).join('')||'<div class="empty">No purchase recommended.</div>';}
function energy(){if(!result)return;const x=[[`${result.comparison.shiftedJobs} run(s) shifted`,'Only when work stayed scheduled, lateness did not worsen, and modeled cost did not increase.'],[`Peak ${result.baseline.peakKw} → ${result.proposed.peakKw} kW`,`${result.comparison.peakReductionKw} kW modeled reduction.`],[`Peak tariff ${input.energy.peakStart}–${input.energy.peakEnd}`,`${result.proposed.jobs.filter(peak).length} run(s) overlap the peak-rate window.`],[`Month peak ${input.energy.monthlyPeakKw} kW`,'Demand savings are conditional on the final billed monthly peak.']];$('energy-insights').innerHTML=x.map(a=>`<article class="insight-card"><strong>${esc(a[0])}</strong><p>${esc(a[1])}</p></article>`).join('');}
function pilotDetail(k){const p=pilots[k]||pilots.rkg;active=k;$('pilot-detail-title').textContent=`${p.name} · ${p.id}`;document.querySelectorAll('#pilot-tabs [data-pilot]').forEach(b=>b.classList.toggle('active',b.dataset.pilot===k));$('pilot-detail').innerHTML=`<div class="pilot-detail-block"><h3>Recorded workflow</h3><p>${esc(p.flow)}</p><div class="pilot-order"><strong>Scope</strong><span>${p.orders} orders · ${p.cycles} cycles · operator rating ${p.rating}/5</span><span>Workbook-derived pilot data, separate from the synthetic demo.</span></div></div><div class="pilot-detail-block"><h3>Example decisions</h3>${p.moves.map((m,i)=>`<div class="pilot-plan"><strong>${i+1}</strong><span>${esc(m)}</span></div>`).join('')}</div>`;}
function pilotCards(){$('pilot-cards').innerHTML=Object.entries(pilots).map(([k,p])=>`<article class="pilot-card"><span class="eyebrow">RECORDED PILOT · ${esc(p.dates)}</span><h2>${esc(p.name)}</h2><p>${esc(p.flow)}</p><div class="pilot-kpis"><div class="pilot-kpi"><span>Orders</span><strong>${p.orders}</strong></div><div class="pilot-kpi"><span>Planning</span><strong>−${p.planning}%</strong></div><div class="pilot-kpi"><span>Energy</span><strong>−${p.energy}%</strong></div><div class="pilot-kpi"><span>Peak</span><strong>−${p.peak}%</strong></div></div><button data-pilot="${k}">View decisions</button></article>`).join('');pilotDetail(active);}
const base=renderAll;renderAll=function(){base();control();procurement();energy();pilotCards();};
document.addEventListener('DOMContentLoaded',()=>{$('show-pilots').onclick=()=>$('pilots-dialog').showModal();$('close-pilots').onclick=()=>$('pilots-dialog').close();document.addEventListener('click',e=>{const p=e.target.closest('[data-pilot]');if(p){pilotDetail(p.dataset.pilot);return}const b=e.target.closest('[data-create-po]');if(!b)return;openPo(b.dataset.createPo);$('po-qty').value=n(b.dataset.qty);const m=(input.materials||[]).find(x=>x.id===b.dataset.createPo);if(m?.supplierId)$('po-supplier').value=m.supplierId;const s=(input.suppliers||[]).find(x=>x.id===$('po-supplier').value);$('po-date').value=addDays(input.shift.date,s?.leadDays||0)});});
})();
